//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Ezequiel Demetras/Documents/Projetos/PgnConverter/src/Pgn.Compiler/Pgn.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Pgn.Compiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PgnParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPgnListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PgnParser.pgn_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPgn_info([NotNull] PgnParser.Pgn_infoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PgnParser.pgn_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPgn_info([NotNull] PgnParser.Pgn_infoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PgnParser.info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfo([NotNull] PgnParser.InfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PgnParser.info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfo([NotNull] PgnParser.InfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PgnParser.attrs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrs([NotNull] PgnParser.AttrsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PgnParser.attrs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrs([NotNull] PgnParser.AttrsContext context);
}
} // namespace Pgn.Compiler
